website/auth.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash
from flask import redirect
from flask import url_for

from flask_login import login_user
from flask_login import login_required
from flask_login import logout_user
from flask_login import current_user

from werkzeug.security import generate_password_hash
from werkzeug.security import check_password_hash

from .utility import AllTimezones, UTC, UpdateCurrentTimezone
from .models import User
from . import db

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form.get('name')
        password = request.form.get('password')
        remember = request.form.get('remember')

        user = User.query.filter_by(name=name).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=remember)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('User does not exist.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'POST':
        name = request.form.get('name')
        in_game_name = request.form.get('in_game_name')
        timezone = request.form.get('timezone')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user_settings_changed = False
        user = User.query.filter_by(name=name).first()
        if in_game_name != user.in_game_name:
            if not in_game_name:
                flash('In-game name can\'t be empty', category='error')
            else:
                user.in_game_name = in_game_name
                user_settings_changed = True

        if timezone != user.timezone:
            user.timezone = timezone
            user_settings_changed = True
        
        if password1:
            if password1 != password2:
                flash('Passwords don\'t match', category='error')
                user_settings_changed=False
            else:
                user.password = generate_password_hash(password1)
                user_settings_changed = True

        if user_settings_changed:
            db.session.add(user)
            db.session.commit()
            UpdateCurrentTimezone()
            flash('User settings updated', category='success')
    
    return render_template('profile.html', user=current_user, timezones=AllTimezones())

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form.get('name')
        in_game_name = request.form.get('in_game_name')
        timezone = UTC()
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(name=name).first()
        if user:
            flash('User already exists.', category='error')
        elif len(name) < 3:
            flash('Name must be greater than 2 characters', category='error')
        elif len(in_game_name) < 1:
            flash('In-game name must be filled in', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match', category='error')
        elif len(password1) < 5:
            flash('Password must be at least 5 characters', category='error')
        else:
            new_user = User(name=name, in_game_name=in_game_name, timezone=timezone, password=generate_password_hash(password1))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created', category='success')
            
            return redirect(url_for('views.home'))

    return render_template("register.html")

website/views.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash

from flask_login import login_required
from flask_login import current_user

from .utility import Now, Today, LocalDate, UniversalDate, Duration, FormData, Sort

from .roles import Role, role_required

from .models import Mechlist, User
from .models import Build, Mech
from .models import Tournament, Event, Attendance, SharedEvent, Map
from .models import Dropdeck, DropdeckLine
from .parser import parse_mechlist
from .scraper import scrape_url
from . import db

views = Blueprint('views', __name__)

## ------------------------------------------------------------------------------------------------
##  Route:
##      /
##      /home
## ------------------------------------------------------------------------------------------------

@views.route('/', methods=['GET', 'POST'])
@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    events = Event.ActiveEvents()
    event_ids = [event.id for event in events]
    attended_events = Attendance.query.filter(Attendance.user_id == current_user.id, Attendance.event_id.in_(event_ids)).all()
    attendance = [item.event_id for item in attended_events]
    stats = {
        "users": User.Total(),
        "mechs": Mechlist.Total(),
        "builds": Build.Total(),
        "events": len(events)
    }
    return render_template("home.html", user=current_user, stats=stats, events=events, attendance=attendance)

## ------------------------------------------------------------------------------------------------
##  Route:
##      /mechlist-update
##      /mechlist-search
##      /mechlist-add
## ------------------------------------------------------------------------------------------------

@views.route('/mechlist-update', methods=['GET', 'POST'])
@login_required
def mechlist_update():
    if request.method == 'POST':
        new_mechlist = request.form.get('newMechlist')
        mechs = parse_mechlist(new_mechlist)
        mechlist = Mechlist.query.filter_by(user_id=current_user.id).all()
        for item in mechlist:
            db.session.delete(item)
        
        for mech in mechs.values():
            new_item = Mechlist(user_id=current_user.id, mech_name=mech['Name'])
            db.session.add(new_item)
        
        db.session.commit()

    mechs = Mech.All()
    return render_template('mechlist-update.html', user=current_user, mechs=mechs)

@views.route('/mechlist-search')
@login_required
@role_required(Role.TeamMember)
def mechlist_search():
    users = User.All()
    data = {}
    for user in users:
        mechlist = Mechlist.query.filter_by(user_id=user.id).all()
        data[user.in_game_name] = mechlist

    team_total = Mechlist.TeamTotal()

    return render_template('mechlist-search.html', data=data, team_total=team_total)

@views.route('/mechlist-add', methods=['POST'])
@login_required
def mechlist_add():
    data = request.get_json()
    id = data.get('id')
    mech = Mech.query.get(id)

    response = {}
    if mech:
        item = Mechlist.query.filter_by(user_id=current_user.id, mech_name=mech.name).first()
        if not item:
            new_item = Mechlist(user_id=current_user.id, mech_name=mech.name)
            db.session.add(new_item)
            db.session.commit()

        response['success'] = True
        response['mech'] = mech.name
        response['chassis'] = mech.chassis
        response['side'] = mech.side
        response['tonnage'] = mech.tonnage
        response['class'] = mech.weight_class
        response['type'] = mech.chassis_type
    else:
        response['success'] = False
        response['error'] = f'Selected mech wasn\'t found in the database.'

    return response

## ------------------------------------------------------------------------------------------------
##  Route:
##      /calendar
## ------------------------------------------------------------------------------------------------

@views.route('/calendar')
@login_required
@role_required(Role.TeamMember)
def calendar():
    return render_template('not-implemented.html')

## ------------------------------------------------------------------------------------------------
##  Route:
##      /tournaments
##      /tournament-add
##      /tournament-edit/tournament_id
##      /tournament-finish/tournament_id
## ------------------------------------------------------------------------------------------------

@views.route('/tournaments')
@login_required
@role_required(Role.TeamMember)
def tournaments():
    all_tournaments = Tournament.query.all()
    return render_template('tournaments.html', tournaments=all_tournaments)

@views.route('/tournament-add', methods=['GET', 'POST'])
@login_required
@role_required(Role.TeamMember)
def tournament_add():
    if request.method == 'POST':
        form_data = FormData(request.form)
        tournament = Tournament().Add(data=form_data)
        db.session.add(tournament)
        db.session.commit()

        all_tournaments = Tournament.query.all()
        return render_template('tournaments.html', tournaments=all_tournaments)
    else:
        tournament = {
            "id": "",
            "name": "",
            "full_name": "",
            "team_size": "",
            "is_active": False
        }
        return render_template('tournament-edit.html', tournament=tournament)

@views.route('/tournament-edit/<int:tournament_id>', methods=['GET', 'POST'])
@login_required
@role_required(Role.TeamMember)
def tournament_edit(tournament_id):
    if request.method == 'POST':
        tournament = Tournament.query.filter_by(id=tournament_id).first()
        tournament.name = request.form.get('name')
        tournament.full_name = request.form.get('full_name')

        db.session.add(tournament)
        db.session.commit()
    else:
        tournament = Tournament.query.filter_by(id=tournament_id).first()
        if tournament:
            if tournament.is_active:
                return render_template('tournament-edit.html', tournament=tournament)
            else:
                flash('Tournament finished and can\'t be edited.', category='error')
        else:
            flash('Tournament id wasn\'t found in the database.', category='error')

    all_tournaments = Tournament.query.all()
    return render_template('tournaments.html', tournaments=all_tournaments)

@views.route('/tournament-finish/<int:tournament_id>')
@login_required
@role_required(Role.TeamMember)
def tournament_finish(tournament_id):
    tournament = Tournament.query.filter_by(id=tournament_id).first()
    tournament.is_active = False

    db.session.add(tournament)
    db.session.commit()

    all_tournaments = Tournament.query.all()
    return render_template('tournaments.html', tournaments=all_tournaments)

## ------------------------------------------------------------------------------------------------
##  Route:
##      /events
##      /event-add
##      /event-edit/<int:event_id>
##      /event-cancel/<int:event_id>
##      /event-view/<int:event_id>
##      /event-sign-up/<int:event_id>
##      /event-withdraw/<int:event_id>
##      /event-share
##      /events/shared/<string:url>
##      /delete-expired-links
## ------------------------------------------------------------------------------------------------

def EventList():
    active_events = Event.ActiveEvents()
    passed_events = Event.PassedEvents()
    return render_template('events.html', events=active_events, passed=passed_events)

def RenderEventView(event_id):
    event = Event.query.get(event_id)
    dropdecks = []
    pilots_assigned = {}
    mechs_used = {}
    all_users = {user.id: user.in_game_name for user in User.All()}
    event_dropdecks = Dropdeck.query.filter_by(event_id=event_id, is_finalized=True).all()
    for dropdeck in event_dropdecks:
        rows = []
        drop_tonnage = 0
        for row in dropdeck.rows:
            if row.pilot_id and row.pilot_id in all_users:
                pilot_name = all_users[row.pilot_id]
                if pilot_name in pilots_assigned:
                    pilots_assigned[pilot_name] += 1
                else:
                    pilots_assigned[pilot_name] = 1
            if row.mech_id:
                mech = Mech.query.get(row.mech_id)
                if mech.chassis in mechs_used:
                    mechs_used[mech.chassis] += 1
                else:
                    mechs_used[mech.chassis] = 1
                drop_tonnage += mech.tonnage
            
            item = {
                "pilot": all_users[row.pilot_id] if row.pilot_id and row.pilot_id in all_users else "",
                "spawn": row.spawn,
                "mech": mech.name if row.mech_id else "",
                "chassis": mech.chassis if row.mech_id else "",
                "tonnage": mech.tonnage if row.mech_id else "",
                "class": mech.weight_class if row.mech_id else "",
                "build": {
                    "name": row.build.name if row.build else "",
                    "code": row.build.code if row.build else "",
                    "loadout": row.build.loadout if row.build else ""
                },
                "notes": row.notes
            }
            rows.append(item)
        
        item = {
            "id": dropdeck.id,
            "starting_side": dropdeck.starting_side,
            "name": dropdeck.name,
            "drop_number": dropdeck.drop_number,
            "tonnage": drop_tonnage,
            "map": dropdeck.map.name if dropdeck.map else "",
            "rows": rows
        }
        dropdecks.append(item)

    Sort(dropdecks, 'drop_number')
    
    stats = {
        "mechs": sorted(mechs_used.items(), key=lambda x: x[1], reverse=True),
        "pilots": pilots_assigned
    }
    data = {
        "event": event.name,
        "event_id": event.id,
        "map_planner_link": event.map_planner_link if event.map_planner_link else "",
        "stats": stats,

website/templates/dropdecks.html
{% extends "template.html" %}
{% block title %}Dropdecks{% endblock %}
{% block head %}
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
{% endblock %}
{% block ContentHeader %}Dropdecks{% endblock %}
{% block content %}
  <table id="dropdecks" class="table table-dark table-sm table-bordered table-striped">
    <thead>
    <tr>
        <th>WIP</th>
        <th><span class="d-none d-lg-block">Tournament</span></th>
        <th>Event</th>
        <th>Drop</th>
        <th class="d-none d-lg-table-cell">Name</th>
        <th class="d-none d-lg-table-cell">Map</th>
        <th class="d-none d-lg-table-cell">Team</th>
        <th class="d-none d-lg-table-cell">Author</th>
        <th>#</th>
    </tr>
    </thead>
    <tbody>
      {% for dropdeck in dropdecks %}
      <tr>
        <td class="align-middle">{% if not dropdeck.is_finalized %}<i class="far fa-check-square text-success"></i>{% endif %}</td>
        <td class="align-middle">{{ dropdeck.event.tournament.name }}</td>
        <td class="align-middle">{{ dropdeck.event.name }}</td>
        <td class="align-middle">{{ dropdeck.drop_number }}</td>
        <td class="align-middle d-none d-lg-table-cell">{{ dropdeck.name }}</td>
        <td class="align-middle d-none d-lg-table-cell">{{ dropdeck.map.name }}</td>
        <td class="align-middle d-none d-lg-table-cell">{% if dropdeck.starting_side == 1 %}Team 1{% else %}Team 2{% endif %}</td>
        <td class="align-middle d-none d-lg-table-cell">{{ dropdeck.author.in_game_name }}</td>
        <td class="align-middle"><a class="text-lightblue" href="{{ url_for('views.dropdeck_edit', dropdeck_id=dropdeck.id)}}" title="Edit dropdeck"><i class="far fa-edit"></i></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}
{% block scripts %}
  <!-- DataTables  & Plugins -->
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
  
  <!-- Page specific scripts -->
  <script>
    $(function () {
      $("#dropdecks").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false, "pageLength": 15,
        "columnDefs": [{ orderable: false, targets: 8 }],
        "order": [[0, 'desc'], [2, 'asc'], [3, 'asc']],
        "buttons": [
          {
            text: "Add",
            className: "btn-success",
            action: function () {
              location.assign("{{ url_for('views.dropdeck_add') }}");
            }
          }
        ]
      }).buttons().container().appendTo('#dropdecks_wrapper .col-md-6:eq(0)');
    });
  </script>
{% endblock %}

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MWO Team Manager | Log in</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/css/adminlte.min.css') }}">
</head>
<body class="hold-transition login-page">
  <div class="login-box">
      <div class="login-logo">
          <b>MWO Team Manager</b>
      </div>
      
      <!-- /.login-logo -->
      <div class="card">
          <div class="card-body login-card-body">
          <p class="login-box-msg">Sign in to start your session</p>

          <form method="post">
              <div class="input-group mb-3">
              <input type="text" id="name" name="name" class="form-control" placeholder="User">
              <div class="input-group-append">
                  <div class="input-group-text">
                  <span class="fas fa-user"></span>
                  </div>
              </div>
              </div>
              <div class="input-group mb-3">
              <input type="password" id="password" name="password" class="form-control" placeholder="Password">
              <div class="input-group-append">
                  <div class="input-group-text">
                  <span class="fas fa-lock"></span>
                  </div>
              </div>
              </div>
              <div class="row">
              <div class="col-8">
                  <div class="icheck-primary">
                  <input type="checkbox" id="remember" name="remember">
                  <label for="remember">
                      Remember Me
                  </label>
                  </div>
              </div>
              <!-- /.col -->
              <div class="col-4">
                  <button type="submit" class="btn btn-primary btn-block">Sign In</button>
              </div>
              <!-- /.col -->
              </div>
          </form>

          <div class="social-auth-links text-center mb-3">
              <p>- OR -</p>
          </div>
          <!-- /.social-auth-links -->

          <p class="mb-0 text-center">
              <a href="{{ url_for('auth.register') }}" class="text-center">Register a new user</a>
          </p>
          </div>
          <!-- /.login-card-body -->
      </div>
  </div>
  <!-- /.login-box -->

  <!-- Flash messages -->
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
    {% endfor %}
  {% endif %}
  {% endwith %}

  <!-- jQuery -->
  <script src="{{ url_for('static', filename='adminlte/plugins/jquery/jquery.min.js') }}"></script>
  <!-- Bootstrap 4 -->
  <script src="{{ url_for('static', filename='adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <!-- AdminLTE App -->
  <script src="{{ url_for('static', filename='adminlte/js/adminlte.min.js') }}"></script>
</body>
</html>

website/templates/profile.html
{% extends "template.html" %}
{% block title %}User profile{% endblock %}
{% block ContentHeader %}User profile{% endblock %}
{% block content %}
    <div class="container-fluid">
        <form class="form-horizontal" method="post">
            <div class="form-group row">
                <label for="name" class="col-4 col-lg-2 col-form-label">User name</label>
                <div class="col-8 col-lg-4">
                    <input type="text" readonly class="form-control" id="name" name="name" value="{{ user.name }}" readonly>
                </div>
            </div>
            <div class="form-group row">
                <label for="in_game_name" class="col-4 col-lg-2 col-form-label">In-game name</label>
                <div class="col-8 col-lg-4">
                    <input type="text" class="form-control" id="in_game_name" name="in_game_name" value="{{ user.in_game_name }}" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="timezone" class="col-4 col-lg-2 col-form-label">Time zone</label>
                <div class="col-8 col-lg-4">
                    <select class="form-control" id="timezone" name="timezone" required>
                        {% for timezone in timezones %}
                        <option value="{{ timezone }}" {% if user.timezone == timezone %}selected{% endif %}>{{ timezone }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="password1" class="col-4 col-lg-2 col-form-label">New password</label>
                <div class="col-8 col-lg-4">
                    <input type="password" id="password1" name="password1" class="form-control" placeholder="New password">
                </div>
            </div>
            <div class="form-group row">
                <label for="password2" class="col-4 col-lg-2 col-form-label">Repeat password</label>
                <div class="col-8 col-lg-4">
                    <input type="password" id="password2" name="password2" class="form-control" placeholder="Repeat password">
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-4 offset-lg-2 col-8 col-lg-4">
                <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

website/templates/tournament-edit.html
{% extends "template.html" %}
{% block title %}Tournament - Edit{% endblock %}
{% block ContentHeader %}Tournament{% endblock %}
{% block content %}
    {% if tournament.id != "" %}
    <!-- Modal -->
    <div class="modal fade" id="confirmation" tabindex="-1" role="dialog" aria-labelledby="confirmation_title" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="confirmation_title">Finish tournament</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    Finishing a tournament means that you will no longer be able to create events for it.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a href="{{ url_for('views.tournament_finish', tournament_id=tournament.id) }}" class="btn btn-warning">Finish</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Form -->
    <div class="container-fluid">
        <form class="form-horizontal" method="post">
            <div class="form-group row">
                <label for="name" class="col-4 col-lg-2 col-form-label">Short name</label>
                <div class="col-8 col-lg-4">
                    <input type="text" class="form-control" id="name" name="name" value="{{ tournament.name }}" placeholder="Short unique name">
                </div>
            </div>
            <div class="form-group row">
                <label for="full_name" class="col-4 col-lg-2 col-form-label">Full name</label>
                <div class="col-8 col-lg-4">
                    <input type="text" class="form-control" id="full_name" name="full_name" value="{{ tournament.full_name }}" placeholder="Name that will represent tournament in a list">
                </div>
            </div>
            <div class="form-group row">
                <label for="team_size" class="col-4 col-lg-2 col-form-label">Team size</label>
                <div class="col-8 col-lg-4">
                    {% if tournament.id == "" %}
                    <select class="form-control" id="team_size" name="team_size">
                        {% for count in range(1,12) %}
                        <option value="{{ count }}">{{ count }}</option>
                        {% endfor %}
                        <option value="12" selected="selected">12</option>
                    </select>
                    {% else %}
                    <input type="text" class="form-control" id="team_size" name="team_size" value="{{ tournament.team_size }}" readonly>
                    {% endif %}
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-4 offset-lg-2 col-8 col-lg-4">
                    <a href="{{ url_for('views.tournaments') }}" class="btn btn-secondary"><i class="fas fa-angle-left"></i> Back</a>
                    <button type="submit" class="btn btn-success">Save</button>
                    {% if tournament.id != "" %}
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#confirmation">Finish</button>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
{% endblock %}

website/templates/tournaments.html
{% extends "template.html" %}
{% block title %}Tournaments{% endblock %}
{% block head %}
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
{% endblock %}
{% block ContentHeader %}Tournaments{% endblock %}
{% block content %}
  <table id="tournaments" class="table table-dark table-bordered table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th>Team size</th>
        <th>Status</th>
        <th>#</th>
    </tr>
    </thead>
    <tbody>
      {% for tournament in tournaments %}
      <tr>
        <td>{{ tournament.full_name }}</td>
        <td>{{ tournament.team_size }}</td>
        {% if tournament.is_active %}
        <td>
            <div class="text-success">Active</div>
        </td>
        <td><a class="text-lightblue" href="{{ url_for('views.tournament_edit', tournament_id=tournament.id)}}" title="Edit tournament"><i class="far fa-edit"></i></a></td>
        {% else %}
        <td>Finished</td>
        <td></td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}
{% block scripts %}
  <!-- DataTables  & Plugins -->
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
  <script src="{{ url_for('static', filename='adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
  
  <!-- Page specific scripts -->
  <script>
    $(function () {
      $("#tournaments").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false, "pageLength": 15,
        "columnDefs": [{ orderable: false, targets: 3 }],
        "order": [[2, 'asc']],
        "buttons": [
          {
            text: "Add",
            className: "btn-success",
            action: function () {
              location.assign("{{ url_for('views.tournament_add') }}");
            }
          }
        ]
      }).buttons().container().appendTo('#tournaments_wrapper .col-md-6:eq(0)');
    });
  </script>
{% endblock %}